// The domain model is shared with the backend, so it lives in src/domain. This file keeps the old import path working.
export type {
  AlertKind,
  AppNotification,
  BusRecord,
  BusStatus,
  Driver,
  DriverStatus,
  FeedSnapshot,
  FeedStatus,
  IssueReport,
  LocationSource,
  NotificationKind,
  Point,
  Role,
  Route,
  ServiceAlert,
  Stop,
  TransitData,
  Trip,
  TripEvent,
  TripStatus,
  UserAccount,
} from '@/domain/types'
